### ISSUE TITLE
SQLiteScrobbler does not clear cache after SendCachedScrobblesAsync

### ISSUE THREAD

**Issue by coczero** [inflatablefriends/lastfm#103]
This *should* clear the database file right?

**Comment by rikkit** [comment]
It should - though looking at the unit test https://github.com/inflatablefriends/lastfm/blob/master/src/IF.Lastfm.Core.Tests/Scrobblers/ScrobblerTestsBase.cs#L156 there's no assertion to check that. So I suppose it's a bug!

I haven't updated the SQLite package in a while - what package are you using? And do you know if there's a .Net Standard version of SQLite yet - that was the problem last time I looked into updating it. I'll look into fixing this and updating the package tonight.

**Comment by coczero** [comment]
I am pretty sure I use the latest NuGet Package (https://www.nuget.org/packages/Inflatable.Lastfm.SQLite/) which would be 0.2.0.211. I can check once I get home. 

No idea about .Net standard though.

**Comment by rikkit** [comment]
Ok - if you're using sqlite-net-pcl then since there seems to be a .Net Standard version of that package I think I will update ```Inflatable.Lastfm.SQLite``` to target .Net Standard as well. I think most people using this project are using platforms that also support .Net Standard - so this fix would benefit the most people if I retarget the package. I think I remember you saying in another thread that you use v1.x of the main package - so this arrangement should work for you?

**Comment by coczero** [comment]
Yes I use v1.x.
Thanks.

**Comment by rikkit** [comment]
Ran into some issues around csproj formats and my build server - am working on it!

**Comment by rikkit** [comment]
Fixed by #105
