### ISSUE TITLE
Mono Compatibility is Broken or Non-Existent?

### ISSUE THREAD

**Issue by suicvne** [inflatablefriends/lastfm#76]
First, some system background. I'm running Debian 8.1 w/ KDE 4.14. MonoDevelop 5.9.4, the latest Mono from the Mono repositories (NOT Debian's) and the following Mono packages installed: mono-complete, mono-xsp, mono-xsp4. This is enough to get a simple sample up and running. The code sample is as follows (.NET console project in MonoDevelop, targetting "Mono/.Net 4.5"):
Output of mono --version: 

```
Mono JIT compiler version 4.0.2 (Stable 4.0.2.5/c99aa0c Wed Jun 24 10:04:37 UTC 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        LLVM:          supported, not enabled.
        GC:            sgen

```

I pull the latest IF.Lastfm from the official Nuget gallery in MonoDevelop. 

```
using System;
using IF.Lastfm.Core.Api;
using IF.Lastfm.Core.Objects;

namespace LastfmTest
{
    class MainClass
    {
        public static void Main (string[] args)
        {
            Console.WriteLine ("Hello World!");

            var lastfmClient = new LastfmClient ("", ""); //I put my proper keys in here of course
            var response = lastfmClient.User.GetRecentScrobbles ("mrmiketheripper", null, 0, 1);
            LastTrack lastTrack = response.Result.Content [0];

            Console.WriteLine ("{0} - {1}", lastTrack.Name, lastTrack.ArtistName);

            Console.ReadLine ();
        }
    }
}
```

Everything builds and compiles okay, but when I run it, literally nothing happens. My initial "Hello world!" isn't even shown.

![snapshot13](https://cloud.githubusercontent.com/assets/861492/8759055/ce97e4f0-2cba-11e5-9efd-9a88430b20fc.png)

I'm confused as to what's going on here. No errors shown or anything. Surroudning the code in a try-catch produces a similar result.

**Comment by rikkit** [comment]
So you don't see "Hello world!" in the console window... this doesn't look like it's related to the library. Can you step through the code with the debugger?

I can't try out your setup right now, but I can test with my Ubuntu VM on Monday.

**Comment by zumicts** [comment]
If you're not getting the hello world the issue might be something else.  Could you remove last.fm and just run the hello world?

**Comment by Luigifan** [comment]
Removing last.fm and just running the hello world produces no problems. @zumicts

**Comment by rikkit** [comment]
:confused: I'll try and reproduce.

**Comment by Luigifan** [comment]
@rikkit thank you!

**Comment by rikkit** [comment]
@Luigifan Just got back from holiday, sorry I didn't get a chance to test before I went. 

I've tried to reproduce on Ubuntu 14.10 and I can't. I followed the [install instructions here](http://www.mono-project.com/docs/getting-started/install/linux/#debian-ubuntu-and-derivatives). Then I installed ```mono-devel```. Opening the solution, I found that the IF.Lastfm.Core project compiled fine, though checking the references I noticed that MonoDevelop "couldn't find .NETPortable subset" framework 4.5, profile 269, and I wasn't able to reference IF.Lastfm.Core from a new command line project. So I installed the ```referenceassemblies-pcl``` - [it's noted in the install](http://www.mono-project.com/docs/getting-started/install/linux/#usage) but I missed it at first. Then the test program worked (after restarting MonoDevelop).

![screenshot from 2015-07-28 00 38 01](https://cloud.githubusercontent.com/assets/692840/8920525/0afcab60-34c2-11e5-871c-67183e00bedc.png)

MonoDevelop didn't complain when ```referenceassemblies-pcl``` wasn't installed, so that makes me think this could be the problem. Can you check if you have that installed?

**Comment by Luigifan** [comment]
@rikkit I will verify this right now. Who's that guy who has such a good taste in music though? ;)

**Comment by Luigifan** [comment]
@rikkit I installed `referenceassemblies-pcl` and i'm still getting the same results where it just idles, not even a hello world. This is really weird.

**Comment by rikkit** [comment]
Okay.. so the difference between our tests is that yours is from Nuget whereas I'm building from source... could be something wrong with the NuGet package? :confused: I'll test that tonight.

**Comment by Luigifan** [comment]
@rikkit okay thank you! if i have time today I will test from source
