### ISSUE TITLE
Appveyor build is actually failing

### ISSUE THREAD

**Issue by ben-biddington** [inflatablefriends/lastfm#82]
Hi,

It looks like the build is ignoring test failures?:

https://ci.appveyor.com/project/rikkit/lastfm/build/0.2.999.257#L371

(I get the same failure locally)

**Comment by rikkit** [comment]
Hey, thanks for raising this. If I remember right, AppVeyor build used to fail so I'm not sure what's changed. I did migrate from NUnit 2 to 3 a few months ago so that might have caused it.

Test results are still being picked up: https://ci.appveyor.com/project/rikkit/lastfm/build/0.2.999.257/tests so it seems like some kind of AppVeyor config.

Anyway that specific test - ```IF.Lastfm.Core.Tests.Integration.Commands.TrackUpdateNowPlayingCommandTests.UpdatesNowPlaying``` - was originally meant to be a sanity test against the API. Last.fm data keeps changing however and breaks the test. Ideally I'd have a better way of verifying functionality against the real Last.fm API, that runs on a regular schedule and covers all the methods in the API. I haven't got round to making that though - and I'm not sure what form it would take - so for now it might be best to just ignore the integration tests that hit Last.fm.
