### ISSUE TITLE
First HTTP request to lastfm API is very slow (takes aprox 10 secs)

### ISSUE THREAD

**Issue by jjgh** [inflatablefriends/lastfm#84]
Hi,
I'm finding that the first HTTP request I make to the lastfm API is very slow:

`var similarArtists = await myLastfmClient.Artist.GetSimilarAsync("ACDC"));`

This will take aprox 10 seconds to complete, but successive requests will complete in just a matter of milliseconds, as expected.
Could this be possibly related to:

http://stackoverflow.com/questions/16086045/first-call-to-a-net-webservice-is-slow

and to:

http://stackoverflow.com/questions/2519655/httpwebrequest-is-extremely-slow

?

**Comment by jjgh** [comment]
Self answer: yes it's related to that: the first HTTP request tries to detect if there is proxy, slowing the request down. Following the answer at http://stackoverflow.com/a/16087788/988591 I disabled the proxy completely for last.fm by adding this to App.config:

```
<configuration>
    <system.net>
        <defaultProxy>
            <bypasslist>
                <add address="last.fm" />
            </bypasslist>
        </defaultProxy>
    </system.net>
</configuration>
```

**Comment by rikkit** [comment]
Hi @jjgh, I think this is to do with the debugger. At a guess you're building an app and each time you launch the debugger a new "network context" (term i just made up) gets created. If the delay comes from resolving proxies and DNS then I don't think this would happen on a real phone/ computer, because that info will be cached. Either way this seems to be a platform issue.

**Comment by jjgh** [comment]
Thanks for the insight. When I have more time, I'll look into it again and see if I notice a difference between debugging mode and running the built file on its own.
